on: [workflow_call]
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: This is extracted by renovate
        uses: docker://ghcr.io/renovatebot/renovate:42.52.2
      - uses: docker://ghcr.io/renovatebot/renovate:42.32.0
        name: This is NOT extracted by renovate
